
name: release

on:
  push:
    branches-ignore:
      - '!master'
  pull_request:
    branches: 
      - '!master'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: dunno
      run: pwd && ls -la

